import re
import os
from datetime import datetime

def run_material_agent(message: str, user: dict, db) -> dict:
    text = message.strip()
    lower = text.lower()
    
    # Extract Title
    title = ""
    quote_match = re.search(r'["\']([^"\']+)["\']', text)
    if quote_match:
        title = quote_match.group(1)
    else:
        title_match = re.search(r'(?:titled|called|named|notes)\s+([a-zA-Z0-9\s]+?)(?:\s+for|\s+on|\s+with|$)', text, re.IGNORECASE)
        title = title_match.group(1).strip() if title_match else "Lecture Notes"
        
    # Extract Subject / Course Code
    known_subjects = ["Data Structures", "Machine Learning", "Database Systems", "Algorithms", "Software Engineering"]
    subject = ""
    for sub in known_subjects:
        if sub.lower() in lower:
            subject = sub
            break
            
    user_subjects = user.get("subjects", [])
    if not subject and user_subjects:
        subject = user_subjects[0]
    elif not subject:
        subject_match = re.search(r'(?:for|on)\s+([a-zA-Z\s]+?)(?:\s+titled|\s+description|$)', text, re.IGNORECASE)
        subject = subject_match.group(1).strip() if subject_match else "General"
        
    # Extract Description
    description = "Uploaded via Python Faculty AI Agent."
    desc_match = re.search(r'(?:description|details)\s+(?:are|is|be)?\s*(.+)', text, re.IGNORECASE)
    if desc_match:
        description = desc_match.group(1).strip()
        
    # Build unique filename for fileUrl
    safe_title = re.sub(r'\s+', '_', title).lower()
    filename = f"{safe_title}_notes.pdf"
    file_url = f"/uploads/materials/{filename}"
    file_size = 12288 # Mock size 12 KB
    
    # Write dummy placeholder file to uploads/materials
    try:
        uploads_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "uploads", "materials"))
        os.makedirs(uploads_dir, exist_ok=True)
        file_path_on_disk = os.path.join(uploads_dir, filename)
        with open(file_path_on_disk, "w") as f:
            f.write(f"Study materials for {title} on {subject}.\nGenerated by Faculty AI NLU Agent.\n\nDescription: {description}")
    except Exception as e:
        print("Failed to save dummy file to disk:", str(e))
    
    material_doc = {
        "courseCode": subject,
        "title": title,
        "description": description,
        "fileUrl": file_url,
        "fileType": "pdf",
        "fileSize": file_size,
        "uploadedBy": user.get("name", "Faculty Member"),
        "uploadedAt": datetime.utcnow(),
        "downloads": 0,
        "views": 0
    }
    
    db.materials.insert_one(material_doc)
    
    reply = (
        f"🤖 **Faculty Agent (Python)**: Notes package uploaded to student library successfully.\n\n"
        f"*   **Title**: {title}\n"
        f"*   **Subject**: {subject}\n"
        f"*   **Description**: {description}\n"
        f"*   **File Path**: `{file_url}` (12.00 KB)\n\n"
        f"These resources are now instantly discoverable in the Student Study Resources directory."
    )
    
    return {
        "success": True,
        "actionTaken": "UPLOAD_MATERIAL",
        "reply": reply
    }
